-- MySQL Script generated by MySQL Workbench
-- Sun Dec 16 17:46:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cms` ;

-- -----------------------------------------------------
-- Schema cms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cms` DEFAULT CHARACTER SET utf8 ;
USE `cms` ;

-- -----------------------------------------------------
-- Table `cms`.`brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`brands` ;

CREATE TABLE IF NOT EXISTS `cms`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`verticals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`verticals` ;

CREATE TABLE IF NOT EXISTS `cms`.`verticals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `cms`.`verticals` (`name` ASC) ;


-- -----------------------------------------------------
-- Table `cms`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`product` ;

CREATE TABLE IF NOT EXISTS `cms`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `tags` JSON NULL DEFAULT NULL,
  `vertical_id` INT NOT NULL,
  `brand_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT NULL DEFAULT NULL,
  `visibility` TINYINT NULL DEFAULT NULL,
  `start_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `cms`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_vertical1`
    FOREIGN KEY (`vertical_id`)
    REFERENCES `cms`.`verticals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_brand1_idx` ON `cms`.`product` (`brand_id` ASC) ;

CREATE INDEX `fk_product_vertical1_idx` ON `cms`.`product` (`vertical_id` ASC) ;

CREATE INDEX `fk_product_brand1` ON `cms`.`product` (`brand_id` ASC) ;

CREATE INDEX `fk_product_vertical1` ON `cms`.`product` (`vertical_id` ASC) ;


-- -----------------------------------------------------
-- Table `cms`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`category` ;

CREATE TABLE IF NOT EXISTS `cms`.`category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `vertical_id` INT(11) NOT NULL,
  `parent_id` BIGINT(20) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_category_vertical1`
    FOREIGN KEY (`vertical_id`)
    REFERENCES `cms`.`verticals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_category_vertical1_idx` ON `cms`.`category` (`vertical_id` ASC) ;

CREATE INDEX `fk_category_vertical1` ON `cms`.`category` (`vertical_id` ASC) ;


-- -----------------------------------------------------
-- Table `cms`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`country` ;

CREATE TABLE IF NOT EXISTS `cms`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `cms`.`country` (`name` ASC) ;


-- -----------------------------------------------------
-- Table `cms`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`city` ;

CREATE TABLE IF NOT EXISTS `cms`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `country_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_city_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `cms`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_city_country1_idx` ON `cms`.`city` (`country_id` ASC) ;

CREATE INDEX `fk_city_country1` ON `cms`.`city` (`country_id` ASC) ;


-- -----------------------------------------------------
-- Table `cms`.`category_filters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`category_filters` ;

CREATE TABLE IF NOT EXISTS `cms`.`category_filters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `category_id` BIGINT(20) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_category_filters_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `cms`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_category_filters_category1_idx` ON `cms`.`category_filters` (`category_id` ASC) ;

CREATE INDEX `fk_category_filters_category1` ON `cms`.`category_filters` (`category_id` ASC) ;


-- -----------------------------------------------------
-- Table `cms`.`brand_vertical_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`brand_vertical_mapping` ;

CREATE TABLE IF NOT EXISTS `cms`.`brand_vertical_mapping` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand_id` INT NOT NULL,
  `vertical_id` INT NOT NULL,
  `active` TINYINT NULL DEFAULT 1,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_brand_vertical_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `cms`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_brand_vertical_vertical1`
    FOREIGN KEY (`vertical_id`)
    REFERENCES `cms`.`verticals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_brand_vertical_brand1_idx` ON `cms`.`brand_vertical_mapping` (`brand_id` ASC) ;

CREATE INDEX `fk_brand_vertical_vertical1_idx` ON `cms`.`brand_vertical_mapping` (`vertical_id` ASC) ;

CREATE INDEX `fk_brand_vertical_brand1` ON `cms`.`brand_vertical_mapping` (`brand_id` ASC) ;

CREATE INDEX `fk_brand_vertical_vertical1` ON `cms`.`brand_vertical_mapping` (`vertical_id` ASC) ;


-- -----------------------------------------------------
-- Table `cms`.`phy_entity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`phy_entity` ;

CREATE TABLE IF NOT EXISTS `cms`.`phy_entity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `city_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  `lat` DECIMAL(6,4) NOT NULL,
  `lon` DECIMAL(6,4) NOT NULL,
  `merchant_id` INT NULL DEFAULT NULL,
  `type` VARCHAR(45) NOT NULL,
  `tags` JSON NULL DEFAULT NULL,
  `active` TINYINT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_phy_entity_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `cms`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phy_entity_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `cms`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_phy_entity_city1_idx` ON `cms`.`phy_entity` (`city_id` ASC) ;

CREATE INDEX `fk_phy_entity_country1_idx` ON `cms`.`phy_entity` (`country_id` ASC) ;

CREATE INDEX `fk_phy_entity_city1` ON `cms`.`phy_entity` (`city_id` ASC) ;

CREATE INDEX `fk_phy_entity_country1` ON `cms`.`phy_entity` (`country_id` ASC) ;


-- -----------------------------------------------------
-- Table `cms`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`event` ;

CREATE TABLE IF NOT EXISTS `cms`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `phy_entity_id` INT NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `tags` JSON NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `udpated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_event_physical_entity1`
    FOREIGN KEY (`phy_entity_id`)
    REFERENCES `cms`.`phy_entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_event_physical_entity1_idx` ON `cms`.`event` (`phy_entity_id` ASC) ;

CREATE INDEX `fk_event_physical_entity1` ON `cms`.`event` (`phy_entity_id` ASC) ;


-- -----------------------------------------------------
-- Table `cms`.`sku`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`sku` ;

CREATE TABLE IF NOT EXISTS `cms`.`sku` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `offer_price` INT NOT NULL,
  `event_id` INT NULL DEFAULT NULL,
  `product_id` BIGINT(20) NOT NULL,
  `merchant_id` INT NOT NULL,
  `tags` JSON NULL DEFAULT NULL,
  `pay_type_supported` JSON NULL DEFAULT NULL,
  `long_rich_desc` JSON NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `udpated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_sku_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `cms`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sku_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `cms`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sku_product1_idx` ON `cms`.`sku` (`product_id` ASC) ;

CREATE INDEX `fk_sku_event1_idx` ON `cms`.`sku` (`event_id` ASC) ;

CREATE INDEX `fk_sku_product1` ON `cms`.`sku` (`product_id` ASC) ;

CREATE INDEX `fk_sku_event1` ON `cms`.`sku` (`event_id` ASC) ;


-- -----------------------------------------------------
-- Table `cms`.`product_category_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`product_category_mapping` ;

CREATE TABLE IF NOT EXISTS `cms`.`product_category_mapping` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `product_id` BIGINT(20) NULL DEFAULT NULL,
  `category_id` BIGINT(20) NULL DEFAULT NULL,
  `active` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_vertical_mapping_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `cms`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_vertical_mapping_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `cms`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_vertical_mapping_product1_idx` ON `cms`.`product_category_mapping` (`product_id` ASC) ;

CREATE INDEX `fk_product_vertical_mapping_category1_idx` ON `cms`.`product_category_mapping` (`category_id` ASC) ;

CREATE INDEX `fk_product_vertical_mapping_product1` ON `cms`.`product_category_mapping` (`product_id` ASC) ;

CREATE INDEX `fk_product_vertical_mapping_category1` ON `cms`.`product_category_mapping` (`category_id` ASC) ;


-- -----------------------------------------------------
-- Table `cms`.`sku_product_entity_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`sku_product_entity_mapping` ;

CREATE TABLE IF NOT EXISTS `cms`.`sku_product_entity_mapping` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku_id` BIGINT(20) NOT NULL,
  `product_id` BIGINT(20) NOT NULL,
  `phy_entity_id` INT NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_sku_product_store_mapping_sku2`
    FOREIGN KEY (`sku_id`)
    REFERENCES `cms`.`sku` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sku_product_store_mapping_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `cms`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sku_product_store_mapping_phy_entity1`
    FOREIGN KEY (`phy_entity_id`)
    REFERENCES `cms`.`phy_entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sku_product_store_mapping_product1_idx` ON `cms`.`sku_product_entity_mapping` (`product_id` ASC) ;

CREATE INDEX `fk_sku_product_store_mapping_phy_entity1_idx` ON `cms`.`sku_product_entity_mapping` (`phy_entity_id` ASC) ;

CREATE INDEX `fk_sku_product_store_mapping_sku2` ON `cms`.`sku_product_entity_mapping` (`sku_id` ASC) ;

CREATE INDEX `fk_sku_product_store_mapping_product1` ON `cms`.`sku_product_entity_mapping` (`product_id` ASC) ;

CREATE INDEX `fk_sku_product_store_mapping_phy_entity1` ON `cms`.`sku_product_entity_mapping` (`phy_entity_id` ASC) ;


-- -----------------------------------------------------
-- Table `cms`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`person` ;

CREATE TABLE IF NOT EXISTS `cms`.`person` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `meta` JSON NULL,
  `is_active` BIGINT(1) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
